---
# Version of applications
 - docker_base:
      pdns: debian:8.7
      pdns_recursor: debian:8.7
 
 - pdns:
      pdns: 4.0.4-1pdns.jessie
      pdns-backend-mysql: 4.0.4-1pdns.jessie
 
 - pdns_recursor:
