---
version: '3'
services:
  pdns-server:
    container_name: pdns-server
    build: 
      context: ./pdns-server
      args:
        PDNS_VERSION: 4.0.4-1pdns.jessie
        PDNS_MYSQL_VERSION: 4.0.4-1pdns.jessie
    depends_on:
      - pdns-db
    links:
      - pdns-db
      - pdns-recursor
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8001:8001/tcp"
    env_file:
      - ./pdns-server.env
    entrypoint:
      - "entrypoint.sh"
      - "-e"
      - "-t"
      - "60"
      - "-w"
      - "pdns-db:3306"
    restart: always

  pdns-recursor:
    container_name: pdns-recursor
    build: 
      context: ./pdns-recursor
      args:
        PDNS_RECURSOR_VERSION: 3.6.2-2+deb8u3
    env_file:
      - ./pdns-recursor.env
    entrypoint:
      - "entrypoint.sh"
      - "-e"

  pdns-admin:
    container_name: pdns-admin
    build: 
      context: ./pdns-admin
      args:
        POWERADMIN_VERSION: 2.1.7
    depends_on:
      - pdns-db
    links:
      - pdns-db
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    env_file:
      - ./pdns-admin.env
    entrypoint:
      - "entrypoint.sh"
      - "-e"
      - "-t"
      - "60"
      - "-w"
      - "pdns-db:3306"
    restart: always

  pdns-db:
    container_name: pdns-db
    build: ./pdns-db/
    env_file:
      - ./pdns-db.env
    volumes:
      - /var/lib/docker/volumes/pdns-db:/var/lib/mysql