---
version: '3'
services:
  pdns:
    image: pdns:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      PDNS_setuid: pdns
      PDNS_setgid: pdns
    links:
      - db

  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: 123456
      MYSQL_RANDOM_ROOT_PASSWORD: 123456
    ports:
      - "127.0.0.1:3306:3306"
